### ISSUE TITLE
静态资源路径配置不正确

### ISSUE THREAD

**Issue by shampoo6** [shampoo6/SpringWebMvc#3]

**Comment by shampoo6** [comment]
```yml
spring:
  data:
    mongodb:
      database: "test3"
      username: "dbAdmin"
      password: "123456"
  resources:
    static-locations: classpath:static/ # 添加这个地址，就能直接访问到static目录下的静态资源
```
